### ISSUE TITLE
What is your Keras and Tensorflow version? 

### ISSUE THREAD

**Issue by wjtan99** [AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection#22]
Thanks for sharing your great work. 
I try to reproduce your embedding part. What is your Keras and TF version?

**Comment by AlbertoSabater** [comment]
Hi! REPP does not need any TF or Pytorch library, since it just uses scikit-learn for the matching algorithms.
The ML library is dependent on the model you use to extract the embeddings. In my [case of YOLOv3](https://github.com/AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection/blob/master/demos/YOLOv3/yolo_requirements.txt) TF 1.13.1 and Keras 2.2.4.

**Comment by wjtan99** [comment]
Yes, I was asking about the YOLOv3 Keras and TF  versions. Thanks a lot for your quick reply. 
I still could not get it run. What Python version do you have?

**Comment by wjtan99** [comment]
Never mind. I read in other discussions that the no-embedding (appearance) works as well as with appearance. That is good for me.
